name: Deploy PHP

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy PHP Site
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          rm -rf /var/www/mvc.lucasbrum.net
          git clone git@github.com:sistematico/php-mvc.git /var/www/mvc.lucasbrum.net
          cd /var/www/mvc.lucasbrum.net
          #git checkout HEAD^ database/database.sqlite
          #git pull
          composer install
          composer dump-autoload -o